services:
  root-scripts:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    tty: true

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /apps/web
    volumes:
      - ./apps/web:/apps/web
      - web_node_modules:/apps/web/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING_INTERVAL=250
      - NEXT_PUBLIC_TOAST_CHECKIN_POST_URL=https://loqnooocmcuthedsduch.supabase.co/functions/v1/toast_checkin
    command: sh -lc "sleep infinity"

volumes:
  web_node_modules:
